schema: "classroom50/repo-config/v1"
classroom: "etc5523"
assignment: "assignment-3"
owner:
  username: "fontikar"
  id: 12161802
  accepted_at: "2026-10-07T01:56:26Z"
source:
  owner: "ETC5523-2026"
  owner_id: 265932295
  repo: "assignment-3"
  branch: "main"
